### ISSUE TITLE
Raw Data Downloading 

### ISSUE THREAD

**Issue by shawaf92** [clariusdev/mobileapi#10]
Hi ,

There's no issue here just need to understand more how is raw data downloading is working 
I made many test sometimes it's very small size like 25 mb and sometimes it's 180 mb 
Does it work per cine ?( I mean if i run capture cine and then download raw data will it download the raw data for this cine only or all the raw data for past cines ) 

Thanks

**Comment by clariusk** [comment]
yes, when you turn data on, it buffers on the probe device. when you then make a single capture, it will just download the corresponding frame, and when making a cine capture, it will download the last X seconds of data, assuming that it is still buffered - note that buffer is of fixed length on the probe device, so scrolling back in the cine and downloading may not yield any raw data if it has been overwritten

**Comment by shawaf92** [comment]
okay , how much time it still buffered after taking a cine ? 
and assuming the current scenario for take 4 cines from 3rd party app  : 
1- Capture Cine 1 -> Download Raw Data -> Raw_Data1.tar  
2- Capture Cine 2 -> Download Raw Data  -> Raw_Data2.tar
3- Capture Cine 3 -> Download Raw Data -> Raw_Data3.tar  
4- Capture Cine 4 -> Download Raw Data -> Raw_Data4.tar  

Will it that work (having raw data tar file for every cine) or Raw Data 2 will have raw data for cine 1 and 2 and so on . 
Cause i saw that only Raw_Data1.tar that has normal size and then next ones getting bigger .

**Comment by clariusk** [comment]
buffer is fixed size, so not time dependent, depends on scan settings
buffering/downloading raw data works as follows:
- scan
- freeze
- select frame(s)
- capture (cine 1)
- unfreeze
- scan
- freeze
- select frame(s)
- capture (cine 2)
...

**Comment by shawaf92** [comment]
So following on that I have been trying this order to download the data 
But there are many stability problems and result usually don't have the correct data 

**I was doing the following from 3rd party app depending on mobile API** 
- scan (capture cine) then (freeze) then (download row data)  
But always download is interrupted by many things 
-- `Port is closed (Write of 96 bytes failed with error: Bad file descriptor)`
-- Receive empty raw data 
--`(Wrong size returned when trying to read 65535 bytes at offset 65535 from block raw data (got 0 bytes))`
And in case of case succeded to download data, it returns with one 1:3 of supposed +50 mb 


So How can I avoid these exceptions, what's the best scenario?

**Comment by shawaf92** [comment]
Any help with these issues ?

**Comment by clariusk** [comment]
we'll have a team member take a look, and try and reproduce, thanks for reporting.

**Comment by shawaf92** [comment]
Hi Kris  , 
were the team able to reporduce these issues ? should I expect any fix for it soon ?

**Comment by clariusk** [comment]
there have new stable software in pilot (8.4.2 on Android and iOS), and suggest trying this. we'll have some updated api docs as well to go along - app store release likely later this month

**Comment by shawaf92** [comment]
is there a way we can get access to the beta version so I can see if that will help with our product state ? , sorry we have tight deadlines .

**Comment by julien-l** [comment]
Hello, you can access pre-release versions in the "pilot" program: https://support.clarius.com/hc/en-us/articles/360019548852-Joining-the-Pilot-Program.

**Comment by shawaf92** [comment]
Hello Julien, 
Please add me to the testers list on google play:` mshawaf@oncoustics.com`

**Comment by julien-l** [comment]
Hello, I just checked the status of the next Pilot version: it is still undergoing internal testing to ensure stability. It shall be available soon, sorry for the delay.
