### ISSUE TITLE
No PosInfo arraylist when receiving MSG_NEW_PROCESSED_IMAGE

### ISSUE THREAD

**Issue by daudrain** [clariusdev/mobileapi#11]
Using Clarius App 8.0.1, a PA HD, and the latest mobilapi, `data.getParcelableArrayList(MobileApi.KEY_POS_INFO)` always returns null.
Even `data.get(MobileApi.KEY_POS_INFO)` returns null, meaning `KEY_POS_INFO` is set to null.

Is it expected?
What can be done to receive valid `PosInfo`?

Thank you

**Comment by clariusk** [comment]
was the 3D Positional Package purchased with the scanner, if so, you will need to follow the instructions here: https://github.com/clariusdev/motion

**Comment by daudrain** [comment]
This option was not purchased.
