### ISSUE TITLE
Feature Request: Show probe battery status via API

### ISSUE THREAD

**Issue by nnaskov** [clariusdev/mobileapi#15]
## Describe the feature you'd like to request
In our app, we may need to use the probe for a long time in continuous manner. This means that the device may be running low on battery. 

We want to monitor the battery level and alert the user if battery is low, to change it before starting a scan (to avoid the device disconnecting in the middle). 

## Describe the solution you'd like
An API endpoint to retrieve the current battery level (ideally in percentage).

**Comment by clariusk** [comment]
actually, you can already get this info through the ProbeInfo Parcelable
https://github.com/clariusdev/mobileapi/blob/master/mobileapi/src/main/java/me/clarius/mobileapi/ProbeInfo.java
