### ISSUE TITLE
Accessing beta apks via GitHub

### ISSUE THREAD

**Issue by mischkew** [clariusdev/mobileapi#17]
Dear Clarius-Team,

as we're working extensively with the mobileapi for our product, we like to test beta builds early. Most of our devs are enrolled into the beta program. Sometimes, not every developer receives the newest beta build, probably due to impartial roll outs. This makes reproducibility and consistent testing difficult.

On top of that, when I try to report back to you guys, I want to make sure to test the feature on the same phone on a stable version of the Clarius app as well, so that I can give you valuable feedback. That means I have to switch the Clarius app versions frequently. 

The PlayStore beta program does not allow me to unregister/ register for the program within a single day. Thus my development process is slow.

Is it possible for you to also release the beta versions here on GitHub (or some other way), so that 3rd party developers can install the app quickly?

For example, it would have helped for #16 

Best,
Sven

**Comment by julien-l** [comment]
Hi thanks for the suggestion, it's not in our plans currently so I will close this request. We will keep you update if we change our plans in the future, thanks!
