### ISSUE TITLE
Port 0

### ISSUE THREAD

**Issue by MarcoTripoli** [clariusdev/mobileapi#19]
Hello,
I am writing for a problem I encountered while updating the probe and app to the new version.
Since the update the port remains at 0 as in the photo below

![8fd89a9a-2daf-416d-838f-c07c0e575d8c](https://user-images.githubusercontent.com/37769871/161536900-de26c587-a30b-471d-af2c-1f4f292c1d27.jpg)

**Comment by clariusk** [comment]
make sure you have selected the probe, then go into Settings->Scanner->Clarius Cast = "Research", the research setting is only valid with probes that have the research license applied. Otherwise you can choose "Inst" or "Anyone", but the port will be randomized.

**Comment by clariusk** [comment]
also note the Mobile API makes no use of the Casting port, only the Cast API
