### ISSUE TITLE
mobileAPI for iOS

### ISSUE THREAD

**Issue by mattiaspaul** [clariusdev/mobileapi#2]
great work on the android API, we are working on a research project that would require computation on Apple hardware, are they any plans to release a mobileAPI for iOS in the near future? (access to raw video stream would be sufficient, maybe ReplayKit2 could be employed). Thanks

**Comment by clariusk** [comment]
thank you for the feedback, there are no plans to build an iOS specific API, as after some research it seems IPC on that platform is a bit complicated. Investigating ReplayKit is a good idea however if it just the image stream that is required. thanks
