### ISSUE TITLE
Using Mobile API on a WiFi-dependent application

### ISSUE THREAD

**Issue by pcanas** [clariusdev/mobileapi#20]
Hi,

Our team is working on an Android application that uses Clarius' Mobile API. The problem that we are facing is that our app requires to have a stable internet connection, and the device pairing breaks this process.

Ideally, we would like to use the Clarius device via our app while maintaining an internet connection to a network different from Clarius'. Would that be possible to achieve?

Thank you!

**Comment by clariusk** [comment]
yes, the probe's Wi-Fi is the most stable for a reliable connection, however you have other options:
- Connect device and probe to a WLAN that has internet connectivity
- Use LTE on the device for Internet
- See if any devices support multiple Wireless NIC's

First option is probably the best, you just need to monitor performance to see if the WLAN traffic causes degradation of the ultrasound rate

**Comment by pcanas** [comment]
Hi Kris. Thanks for your help, we eventually figured it out.
I am closing this issue, but surely we will interact more in the future :-)
