### ISSUE TITLE
Feature Request: Settings API `BUTTON_USER` set individual sub-settings

### ISSUE THREAD

**Issue by nnaskov** [clariusdev/mobileapi#24]
Hi,

Thanks for fixing #18 . I can verify that the API now works as expected. 

However, this still doesn't solve our use-case. After setting the buttons to be `BUTTON_USER`, there are default Single Click actions, namely - `Freeze` and `Capture Image`. 
![Screenshot_20220613-105313](https://user-images.githubusercontent.com/3404751/173329934-c2061d7c-492f-4e2e-9556-6b49c3f6b2b1.jpg)

We want to have a custom Button Action in our app, so if a Single Click is "Freeze", we constantly get unexpected frozen stream, when we use the buttons in our app. We need all Clarius functionality to be "Disabled", to make it work. This is the desired final setup: 

![Screenshot_20220613-105817](https://user-images.githubusercontent.com/3404751/173329949-2ab22b96-cb82-4a50-a438-a68b59324d36.jpg)

Could you implement an API, which will allow me to Disable all sub-options for a button? For example: 
```
....
  settings.buttonUp = SettingsInfo.BUTTON_USER
  settings.buttonUpSingleClick = SettingsInfo.DISABLED
  settings.buttonUpDoubleClick = SettingsInfo.DISABLED
  settings.buttonUpTripleClick = SettingsInfo.DISABLED
  settings.buttonUpQuadClick = SettingsInfo.DISABLED

  settings.buttonDown = SettingsInfo.BUTTON_USER
  settings.buttonDownSingleClick = SettingsInfo.DISABLED
  settings.buttonDownDoubleClick = SettingsInfo.DISABLED
  settings.buttonDownTripleClick = SettingsInfo.DISABLED
  settings.buttonDownQuadClick = SettingsInfo.DISABLED
...
```

**Comment by julien-l** [comment]
Hello thank you for the feedback, I took note of your request and we will discuss it at our next engineering meeting.
Julien
