### ISSUE TITLE
APK for current app `9.3.3.-hotfix-13+0feaf1dc9e` is missing

### ISSUE THREAD

**Issue by nnaskov** [clariusdev/mobileapi#27]
Hi,

I couldn't find the apk for the current version of the app, `9.3.3.-hotfix-13+0feaf1dc9e`. We keep a copy of those and manually deploy them to some of our devices. 

Could you please include that in the releases as, with the previous versions? 

Thanks
Norbert

**Comment by julien-l** [comment]
Published here: https://github.com/clariusdev/mobileapi/releases/tag/v9.3.3-hotfix. It's the same Mobile API as version 9.3.0.

**Comment by nnaskov** [comment]
Thanks a lot.
