### ISSUE TITLE
App crashes when trying to start using an intent

### ISSUE THREAD

**Issue by davidmatos** [clariusdev/mobileapi#3]
### Observed behaviour 
If we try to use an intent to start the application like this:

`Intent().apply { component = ComponentName(CLARIUS_PACKAGE_NAME, CLARIUS_SERVICE_NAME)}`

the Clarius App will crash right after it starts.

To avoid this we need to manually start the Clarius App.

### Expected behaviour
The Clarius App should start automatically when we invoke the intent: 

`Intent().apply { component = ComponentName(CLARIUS_PACKAGE_NAME, CLARIUS_SERVICE_NAME)}`

### Steps to reproduce
Any app that uses the following intent to run the Clarius App will result in the crashing:
`Intent().apply { component = ComponentName(CLARIUS_PACKAGE_NAME, CLARIUS_SERVICE_NAME)}`

**Comment by julien-l** [comment]
This is a known issue but there is no plan to fix it yet.

**Comment by julien-l** [comment]
For information: a ticket was created for this bug, but no timeline yet.

**Comment by clariusk** [comment]
8.3.0 pilot releasing mid-July with fix
