### ISSUE TITLE
MSG_RETURN_FREEZE's KEY_FREEZE attribute may not reflect the frozen state

### ISSUE THREAD

**Issue by daudrain** [clariusdev/mobileapi#30]
### Description

When a client application is not connected, if user freezes Ultrasound Image stream from Clarius App then a client application that connects to Clarius will get a wrong frozen status when sending a `MSG_GET_FREEZE`.

#### Steps

- Start Clarius App
- Select PA HD3Demo
- Click on Clarius App Freeze button
- Start Mobile API Example
- Menu>Connect
- Menu>Ask freeze state

#### Result

`frozen is false` is displayed

#### Expected result

`frozen is true` is displayed

**Comment by julien-l** [comment]
Issue will be fixed in Clarius App version 10.3.0, thanks for reporting.
