### ISSUE TITLE
Problem with downgrading probe's firmware version

### ISSUE THREAD

**Issue by luohwu** [clariusdev/mobileapi#31]
Hi Clarius team,

I am using ImFusion https://www.imfusion.com/, which get real-time US images from Clarius API to do bone reconstruction. They have support Clarius API for a long time. However, they have some technical problems with updating their software to support the latest Clarius API, and they don’t plan to fix this problem at this moment. However, the research project in our team is urgent, and we need to use their software. Currently, the only solution is downgrade our Clarius software to the v9.3.0. I downloaded the older release and installed it. However, the app can't update probe's firmware. In Clarius v10.*, if the app found that the probe having a different version firmware, it will upload the current version to the probe. .So, I am wandering are there any ways to also downgrade the probe's firmware to v9.3?

![37989b377a99eb93af6dfc71a517778](https://github.com/clariusdev/mobileapi/assets/76627876/7c97930f-af17-4811-bd99-1805849555c8)

**Comment by julien-l** [comment]
Hello unfortunately it is not possible to downgrade the probe firmware from v10.x to v9.x.

Which FW version do you currently have? Note that some features were removed from Mobile API v10.1.1, which might be the cause of issues with ImFusion Clarius plugin, but these features were re-added in v10.3.0 so ensure your probe and Clarius app are upgraded to v10.3.0 and try again.

If you still cannot use the probe with ImFusion's Clarius plugin, maybe you can acquire the images separately and import them into ImFusion?

**Comment by luohwu** [comment]
Hi Julien,

Thanks a lot for your information. So I am using v10.3.0.  The ImFusion team told me there is conflict between ImFusion Clarius Plugin and Clarius APP because of OpenGL. And this deep problem is not easy to fix. 

But anyways, I managed to build a bridge between ImFusion and Clarius using OpenIGTLink, which also make real-time visualization possible in ImFusion.

I close this issue since it's solved.

Have a nice day!
