### ISSUE TITLE
Getting a NO LICENSE response with a real device (we're a licensed academic institution)

### ISSUE THREAD

**Issue by ekvj** [clariusdev/mobileapi#35]
I'm sorry if this is not the intended channel for this but we need some help and were directed here.

We're working on an academic project with our own Android app. Everything works well with the SDK up until we try and connect a real device. Then we simply get a "NO LICENSE" response. 

The scanner ID is "L15HD3032301A0115" if that is of any help.

Thank you in advance!

**Comment by julien-l** [comment]
Hi, that scanner has a license for the [cast SDK](https://github.com/clariusdev/cast), not for the mobile API. The mobile API is not supported anymore and has been replaced by the cast SDK. Give a try to the [Android example](https://github.com/clariusdev/cast/tree/master/examples/cast_android) and let us know if you have issues.

**Comment by clariusk** [comment]
responded via email too to explain, thanks
