### ISSUE TITLE
Question about ProcessedImageInfo.originX/originY 

### ISSUE THREAD

**Issue by daudrain** [clariusdev/mobileapi#5]
Hi,

While testing, I noticed these new fields are set with negative values.

Is it expected?

Thank you,
David

**Comment by clariusk** [comment]
yes, the origin translated from polar co-ordinates may be off the visible pixel surface.

**Comment by daudrain** [comment]
In my case, the origin is inside the visible pixel surface:
![image](https://user-images.githubusercontent.com/3604504/121924240-01641480-cd3c-11eb-8578-efb6ad2e6aad.png)

**Comment by daudrain** [comment]
@clariusk From the image I've provided, should `originX` and `originY` be negative?

**Comment by clariusk** [comment]
yes, sorry it's not clear from the documentation, the image is using cartesian quadrant 3, so negatives make sense. to calculate the pixel location of the start/apex of the image, divide the originX/Y parameters by the micronsPerPixel parameter.

**Comment by daudrain** [comment]
Thank you
