### ISSUE TITLE
Unpublished software - not for clinical use when using a previous APK

### ISSUE THREAD

**Issue by mischkew** [clariusdev/mobileapi#6]
Dear Clarius-Team,
Dear @clariusk,

we're using the Clarius L7 HD devices during a clinical study. For the duration of that study we need to ensure that no software updates happen. Thus, we fixed the Clarius version to 7.3.4. Using the released APK in this repository allows us to do that.

Though it now states that the software is not released for clinical use (see screenshot attached, German language). Can you provide a release that is supported for clinical use?

![telegram-cloud-file-2-200300200852-236414-8751606510081180504](https://user-images.githubusercontent.com/2885832/122228585-490fab00-ceb8-11eb-8416-9680419c26f1.jpg)

Much appreciated!

Thanks,
Sven

**Comment by clariusk** [comment]
one can now download the updated zip file

**Comment by mischkew** [comment]
Dear @clariusk thanks for the quick response.

> one can now download the updated zip file

I tried both apk zips at these links:
- [v8.0.1](https://github.com/clariusdev/mobileapi/releases/tag/v8.0.1)
- [v7.3.4](https://github.com/clariusdev/mobileapi/releases/tag/v7.3.0)

From the GitHub release page. Both APKs still show the "unreleased software" banner. Not sure if I'm looking in the wrong location.

**Comment by clariusk** [comment]
thanks, you can try one more time

**Comment by mischkew** [comment]
Thanks Kris, works as expected now! :)
