### ISSUE TITLE
No notification when switching off PA HD from the probe button 

### ISSUE THREAD

**Issue by daudrain** [clariusdev/mobileapi#7]
Our Android App doesn't get any notification from Clarius Android service when the probe is switched off using the probe button.

Whereas our app does get a notification when the probe is frozen using the probe button or switched off from Clarius App UI.
 
**Versions used**
Mobile API 8.0.1
Clarius App 8.0.1-121
Scanner Software Version 8.0.1-192
Scanne HD Software Version 8.01-185

**Comment by clariusk** [comment]
this is not a currently implemented feature, but we can add it to the queue of requests

**Comment by daudrain** [comment]
Thank you

**Comment by clariusk** [comment]
update: we will add a power event message in next software.
note in current documentation for button events:

//! Note: only button events associated to a user-defined function are sent.
//! For example, if a button is associated to the pre-defined "freeze" function, it will not be sent.
//! Button functions are configured in the app's settings.
