### ISSUE TITLE
Mobile app issue

### ISSUE THREAD

**Issue by MarcoTripoli** [clariusdev/mobileapi#9]
Hi,

I am writing to you because using the Clarius probes through the mobile app I noticed that if the contact detection setting in the Scanner section is active set for example to "3" seconds it happens that the QT Cast project crashes. I tried to solve this problem by putting the "Never" option in place of 3 seconds, but doing so the probe for some reason will never go into Auto Block. I was wondering why and how it could be solved.

Also, another problem I encountered is that with each new connection of the probe to the app the port always changes. Very annoying thing, without remaining fixed as it did in the previous version.
I was wondering if this problem could also be solved

Thanks in advance

**Comment by clariusk** [comment]
is this related to the mobile api or the cast api?

**Comment by MarcoTripoli** [comment]
The issue of random ports and settings is of the mobile api, while the problem of the crash occurs in Cast (Qt) when the probe does not detect any contact.

**Comment by clariusk** [comment]
im not sure why ports make a difference in the mobile api, as there is no need to connect via TCP. We can check the contact detection with Cast API and see what can be reproduced.
